// react-test/src/App.tsx
import { useState } from "react";
import { Table } from "./Table";

function App() {
  const [tableVisible, setTableVisible] = useState(false);

  return (
    <div className="text-center p-4">
      {!tableVisible ? (
        <button
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          onClick={() => {
            setTableVisible(true);
          }}
        >
          Render Table in React
        </button>
      ) : null}

      {tableVisible ? <Table /> : null}
    </div>
  );
}

export default App;

// svelte-test/src/App.svelte
<script lang="ts">
  import "./index.css";
  import Table from "./components/Table.svelte";

  let tableVisible = false;
</script>

<div class="text-center p-4">
  {#if !tableVisible}
    <button
      class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      on:click={() => {
        tableVisible = true;
      }}
    >
      Render Table in Svelte
    </button>
  {:else}
    <Table />
  {/if}
</div>
